version: '3'
tasks:
  deploy:
    desc: Deploying kubenetes Checkout service manifests
    cmds:
      - cmd: |-
          echo "Create a service account for Checkout service"
          kubectl apply -f ./checkoutServiceAccount.yaml
          echo "Create a ClusterIP service for Checkout service"
          kubectl apply -f ./checkoutService.yaml
          echo "Applying the Deployment manifests for Checkout service"
          kubectl apply -f ./checkoutDeployment.yaml
          echo "Deployment for Checkout service completed"